version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    container_name: sis-comanda-postgres
    environment:
      - POSTGRES_DB=sis-comanda
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
    ports:
      - '5440:5432'

  sis-comanda-keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    container_name: sis-comanda-keycloak
    ports:
      - '7080:8080'
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev